/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/account/login': RouteRecordInfo<
      '/account/login',
      '/account/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/me/': RouteRecordInfo<
      '/account/me/',
      '/account/me',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/me/logout': RouteRecordInfo<
      '/account/me/logout',
      '/account/me/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/register': RouteRecordInfo<
      '/account/register',
      '/account/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cart/': RouteRecordInfo<
      '/cart/',
      '/cart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/events/': RouteRecordInfo<
      '/events/',
      '/events',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/events/[eventId]/': RouteRecordInfo<
      '/events/[eventId]/',
      '/events/:eventId',
      { eventId: ParamValue<true> },
      { eventId: ParamValue<false> },
      | never
    >,
    '/events/[eventId]/seating': RouteRecordInfo<
      '/events/[eventId]/seating',
      '/events/:eventId/seating',
      { eventId: ParamValue<true> },
      { eventId: ParamValue<false> },
      | never
    >,
    '/patrons/': RouteRecordInfo<
      '/patrons/',
      '/patrons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/account/login.vue': {
      routes:
        | '/account/login'
      views:
        | never
    }
    'src/pages/account/me/index.vue': {
      routes:
        | '/account/me/'
      views:
        | never
    }
    'src/pages/account/me/logout.vue': {
      routes:
        | '/account/me/logout'
      views:
        | never
    }
    'src/pages/account/register.vue': {
      routes:
        | '/account/register'
      views:
        | never
    }
    'src/pages/cart/index.vue': {
      routes:
        | '/cart/'
      views:
        | never
    }
    'src/pages/events/index.vue': {
      routes:
        | '/events/'
      views:
        | never
    }
    'src/pages/events/[eventId]/index.vue': {
      routes:
        | '/events/[eventId]/'
      views:
        | never
    }
    'src/pages/events/[eventId]/seating.vue': {
      routes:
        | '/events/[eventId]/seating'
      views:
        | never
    }
    'src/pages/patrons/index.vue': {
      routes:
        | '/patrons/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
