spring.application.name=backend
# Import secretes
spring.config.import=optional:./secretes.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/${db_name}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
app.secret.auth.key=${jwt_secrete_auth_key}
app.secrete.remember.key=${jwt_secrete_remember_key}
auth.token.name=AUTH_TOKEN
remember.token.name=REMEMBER_TOKEN
frontend.url=${front_end_url}