spring.application.name=backend
# Import secretes
spring.config.import=optional:./secretes.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/${db_name}
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.datasource.driver-class-name=org.postgresql.Driver
# Force execution of schema.sql and data.sql (remove for production | temp
# use for venu creation and addition when in development)
spring.sql.init.mode=always
# Defer data script execution until JPA is fully initialized
# (attached to spring.sql.init.mode=always)
spring.jpa.defer-datasource-initialization=true
# TODO: move back to "update" before merging to main
spring.jpa.hibernate.ddl-auto=create-drop
# Default timezone for Spring Data JPA to match with Postgres database
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
