# Database access
db_name=DB_NAME
db_username=DB_USERNAME
db_password=DB_PASSWORD

# JWT key used to generate JWT tokens for users
# Should be 32 bites long & only numbers and letters
jwt_secrete_key=32_BIT_SECRETE_KEY
